site_name: ARETE
site_description: AMR/VF LGT focused bacterial genomics analysis workflow
site_author: Beiko Lab
nav:
  - Home: README.md
  - Usage: usage.md
  - FAQ: faq.md
  - Output: output.md
  - Known issues: issues.md
  - Citations: CITATIONS.md
  - Roadmap: ROADMAP.md
  - Contributing: contributing.md
  - Reference:
      - Dataset Size: resource_profiles.md
      - Parameters: params.md
      - Subsampling: subsampling.md
repo_url: https://github.com/beiko-lab/arete
theme:
  name: "readthedocs"
plugins:
  - search
