name: islandpath
description: Genomic island prediction in bacterial and archaeal genomes
keywords:
  - genomes
  - genomic islands
  - prediction
tools:
  - islandpath:
    description: Genomic island prediction in bacterial and archaeal genomes
    homepage: https://github.com/brinkmanlab/islandpath
    documentation: https://github.com/brinkmanlab/islandpath#readme
    tool_dev_url: https://github.com/brinkmanlab/islandpath
    doi: "doi:10.1093/bioinformatics/bty095"
    licence: ["GPL-3.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - genome:
      type: file
      description: |
        Genome file in .gbk or .embl format.

output:
  - gi_list:
      type: file
      description: TSV file listing the predicted genomic islands and their coordinates
      pattern: "*.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@jvfe"
