# This workflow will automatically deploy the mkdocs documentation
# while installing the necessary Python dependencies.
# See https://parkererickson.github.io/portfolio/blog/MkDocsCD/

name: docs

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
      - name: Deploy
        run: |
          git pull
          mkdocs gh-deploy
